# Generated by Django 5.2.5 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_promocao',
            field=models.BooleanField(default=False),
        ),
    ]
