# Generated by Django 5.2.5 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha para calcular automaticamente o valor promocional.', max_digits=5, null=True, verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Está em promoção?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha para calcular automaticamente o % de desconto.', max_digits=10, null=True, verbose_name='Preço Promocional (R$)'),
        ),
    ]
